### ISSUE TITLE
Telltale BoneNames.hashdb

### ISSUE THREAD

**Issue by vladyxd** [RandomTBush/RTB-3DSMax-Scripts#4]
Where is this file supposed to be? I searched every relevant .ttarch2 file, there is no .hashdb file in there, although the script asks for it.

**Comment by RandomTBush** [comment]
That file can be found on this very GitHub page: https://github.com/RandomTBush/RTB-3DSMax-Scripts/tree/main/Scripts/TelltaleHashDBs

You'll want to make a folder in your 3DS Max's "Scripts" folder called "TelltaleHashDBs" and put both [BoneNames.HashDB](https://github.com/RandomTBush/RTB-3DSMax-Scripts/blob/main/Scripts/TelltaleHashDBs/BoneNames.HashDB) and [TexNames.HashDB](https://github.com/RandomTBush/RTB-3DSMax-Scripts/blob/main/Scripts/TelltaleHashDBs/TexNames.HashDB) in there, so that the script can autodetect them upon use.

**Comment by vladyxd** [comment]
Lifesaver! I thought it would've been inside the game's archives! Love!
